language: php

php:
  - 7.2

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer dump-autoload

script: ./vendor/bin/phpunit --configuration=./phpunit.xml --coverage-clover ./build/logs/clover.xml 

after_success:
  - travis_retry php ./vendor/bin/php-coveralls
  
cache:
  directories:
  - $HOME/.composer/cache/files
  - ./vendor
